---
- name: Create receiver systemd service unit
  template:
    src: thanos-receiver.service.j2
    dest: /etc/systemd/system/thanos-receiver.service
    owner: root
    group: root
    mode: 0644
  when:
    - thanos_receiver|bool
  notify: restart thanos-receiver

- name: Create hashring file for receiver
  template:
    src: receiver/hashring.json.j2
    dest: "{{ thanos_config_dir }}/hashring.json"
    owner: root
    group: root
    mode: 0644
  when:
    - thanos_receiver|bool
  notify: restart thanos-receiver

- name: Ensure thanos-receiver service is enabled
  systemd:
    daemon_reload: yes
    name: thanos-receiver
    enabled: yes
  when:
    - thanos_receiver|bool
    - ansible_service_mgr == 'systemd'
  notify: restart thanos-receiver

- name: Check if Service Exists
  stat:
    path: /etc/systemd/system/thanos-receiver.service
  register: service_status
  when:
    - not thanos_receiver
    - thanos_remove_unused|bool

- name: Stop thanos receiver
  systemd:
    name: thanos-receiver
    state: stopped
    enabled: yes
    daemon_reload: yes
  when:
    - not thanos_receiver
    - thanos_remove_unused|bool
    - service_status.stat.exists
    - ansible_service_mgr == 'systemd'

- name: Remove thanos receiver
  file:
    path: /etc/systemd/system/thanos-receiver.service
    state: absent
  when:
    - not thanos_receiver
    - thanos_remove_unused|bool
    - ansible_service_mgr == 'systemd'
