---
prometheus_web_listen_address: 127.0.0.1:9090
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: "http://{{ prometheus_web_listen_address }}"
    basicAuth: false
  - name: thanos
    type: prometheus
    access: proxy
    url: "http://{{ groups['nginx-lb-query'][0] }}:9090"
    basicAuth: false
grafana_security:
  admin_user: admin
  admin_password: admin
