---
thanos_version: 0.24.0
# Defaults to prometheus for receiver
thanos_user: thanos
thanos_group: thanos

# Enable services
thanos_receiver: no
thanos_query: no
thanos_query_frontend: no
thanos_store: no
thanos_compactor: no
thanos_ruler: no
# Purge disabled services from system
thanos_remove_unused: yes

# Paths, directories
thanos_root_dir: /opt/thanos
thanos_config_dir: /etc/thanos
thanos_tsdb_dir: /var/lib/prometheus
thanos_data_dir: /var/lib/thanos

thanos_cluster: "EU1"

# Paths, files
thanos_receiver_pid_path: /var/run/thanos-receiver.pid
thanos_query_pid_path: /var/run/thanos-query.pid
thanos_query_frontend_pid_path: /var/run/thanos-query-frontend.pid
thanos_store_pid_path: /var/run/thanos-store.pid
thanos_compactor_pid_path: /var/run/thanos-compactor.pid
thanos_ruler_pid_path: /var/run/thanos-ruler.pid

thanos_bucket_config: ""

# Calculated section uses variable to
thanos_platform: "linux-amd64"
thanos_release_name: "thanos-{{ thanos_version }}.{{ thanos_platform }}"
thanos_download_fn: "{{ thanos_release_name }}.tar.gz"
thanos_download_url: "https://github.com/thanos-io/thanos/releases/download/v{{ thanos_version }}/{{ thanos_download_fn }}"

thanos_dist_dir: "{{ thanos_root_dir }}/dist"
thanos_bin_dir: "{{ thanos_root_dir }}/current"

thanos_receiver_web_listen_port: "19191"
thanos_receiver_web_listen_address: "0.0.0.0:{{ thanos_receiver_web_listen_port }}"
thanos_query_web_listen_port: "19192"
thanos_query_web_listen_address: "0.0.0.0:{{ thanos_query_web_listen_port }}"
thanos_query_frontend_web_listen_port: "19196"
thanos_query_frontend_web_listen_address: "0.0.0.0:{{ thanos_query_frontend_web_listen_port }}"
thanos_store_web_listen_port: "19193"
thanos_store_web_listen_address: "0.0.0.0:{{ thanos_store_web_listen_port }}"
thanos_compactor_web_listen_port: "19194"
thanos_compactor_web_listen_address: "0.0.0.0:{{ thanos_compactor_web_listen_port }}"

thanos_receiver_grpc_listen_port: "19181"
thanos_receiver_grpc_listen_address: "0.0.0.0:{{ thanos_receiver_grpc_listen_port }}"
thanos_query_grpc_listen_port: "19182"
thanos_query_grpc_listen_address: "0.0.0.0:{{ thanos_query_grpc_listen_port }}"
thanos_store_grpc_listen_port: "19183"
thanos_store_grpc_listen_address: "0.0.0.0:{{ thanos_store_grpc_listen_port }}"

thanos_ruler_query_port: 9090
thanos_ruler_query_url: "http://0.0.0.0:{{ thanos_ruler_query_port }}"
thanos_ruler_alertmanager_port: 80
thanos_ruler_alertmanager_url: "http://alert.thanos.io"
thanos_ruler_eval_interval: 30s
thanos_ruler_web_listen_port: "19195"
thanos_ruler_web_listen_address: "0.0.0.0:{{ thanos_ruler_web_listen_port }}"
thanos_ruler_grpc_listen_port: "19185"
thanos_ruler_grpc_listen_address: "0.0.0.0:{{ thanos_ruler_grpc_listen_port }}"

thanos_ruler_queries: ""

thanos_web_prometheus_url: "http://localhost:9090/"

thanos_receiver_receive_local_endpoint_listen_port: 10907
thanos_receiver_receive_local_endpoint_listen_address: 127.0.0.1:{{ thanos_receiver_receive_local_endpoint_listen_port }}
thanos_receiver_remote_write_listen_port: 10908
thanos_receiver_remote_write_listen_address: 0.0.0.0:{{ thanos_receiver_remote_write_listen_port }}
thanos_receiver_replica: 0
thanos_receiver_replication_factor: 1

thanos_query_stores: ""
thanos_query_frontend_queries: ""
thanos_query_replica_label: replica

thanos_log_format: json

thanos_query_frontend_flags: >-
  --http-address {{ thanos_query_frontend_web_listen_address }}
  --log.format={{ thanos_log_format }}
  {{ thanos_query_frontend_queries }}

thanos_query_flags: >-
  --http-address {{ thanos_query_web_listen_address }}
  --grpc-address {{ thanos_query_grpc_listen_address }}
  --query.replica-label {{ thanos_query_replica_label }}
  --log.format={{ thanos_log_format }}
  {{ thanos_query_stores }}

thanos_receiver_flags: >-
  --tsdb.path {{thanos_tsdb_dir}}
  --http-address {{thanos_receiver_web_listen_address}}
  --grpc-address {{thanos_receiver_grpc_listen_address}}
  --receive.local-endpoint {{ thanos_receiver_receive_local_endpoint_listen_address }}
  --receive.hashrings-file {{ thanos_config_dir }}/hashring.json
  --remote-write.address {{ thanos_receiver_remote_write_listen_address }}
  --receive.replication-factor {{ thanos_receiver_replication_factor }}
  --label "receive_replica=\"{{ thanos_receiver_replica }}\"" 
  --label "receive_cluster=\"{{ thanos_cluster }}\""
  --log.format={{ thanos_log_format }}

thanos_store_flags: >-
  --data-dir {{ thanos_data_dir }}/store
  --objstore.config-file {{ thanos_config_dir }}/bucket_config.yaml
  --http-address {{ thanos_store_web_listen_address }}
  --grpc-address {{ thanos_store_grpc_listen_address }}
  --log.format={{ thanos_log_format }}

thanos_compactor_flags: >-
  --data-dir {{ thanos_data_dir }}/compact
  --objstore.config-file {{thanos_config_dir}}/bucket_config.yaml
  --http-address {{ thanos_compactor_web_listen_address }}
  --consistency-delay  {{ thanos_compactor_delay | default("120m") }}
  --retention.resolution-raw {{ thanos_raw_retention | default("30d") }}
  --retention.resolution-5m {{ thanos_5m_retention | default("180d") }}
  --retention.resolution-1h {{ thanos_1h_retention | default("7300d") }}
  --log.format={{ thanos_log_format }}
  --wait

thanos_ruler_flags: >-
  --http-address {{thanos_ruler_web_listen_address}}
  --grpc-address {{thanos_ruler_grpc_listen_address}}
  --data-dir             {{ thanos_data_dir }}
  --eval-interval        {{ thanos_ruler_eval_interval }}
  --rule-file            "{{ thanos_config_dir }}/*.rules.yaml"
  --alert.query-url      {{ thanos_ruler_query_url }}
  --alertmanagers.url    {{ thanos_ruler_alertmanager_url }}
  {{ thanos_ruler_queries }}
