---
_nginx_upstream_name: thanos-query-frontend
_thanos_query_frontend_port: 19196

nginx_upstreams:
  - name: "{{ _nginx_upstream_name }}"
    strategy: "ip_hash" # "least_conn", etc.
    keepalive: 16 # optional
    servers: "{{ groups['thanos-query-frontend'] | product([':19196']) | map('join') | list  }}"

nginx_vhosts:
  - listen: "9090"
    server_name: "_"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    extra_parameters: |
      location / {
          proxy_pass http://{{ _nginx_upstream_name }};
          proxy_set_header    Host $host;
          
          proxy_connect_timeout 30;
          proxy_send_timeout 30;
      }

nginx_remove_default_vhost: true
